### ISSUE TITLE
Bintray shutdown

### ISSUE THREAD

**Issue by Azuaron** [findify/sqsmock#12]
Bintray is shutting down on May 1. Are there any plans to move findify libraries like sqsmock away from bintray so they can still be accessed?

**Comment by shuttie** [comment]
Yes, but bintray shuts down only the rest APIs on May 1st. Packages are going to be served till 2022.

**Comment by Azuaron** [comment]
JFrog has been somewhat unclear on what will and will not be available following May 1st. But, they did say this in their announcement:

> We will have some short service brown-outs to remind users about the services that are going away on May 1st. (Specific hours will be advertised in the Bintray status page.)

And all our builds broke on the April 12th brownout because dependencies couldn't be found. This tells me that they will break permanently after May 1st.

They also say:

> What happens to my data after Bintray and JCenter are sunset?
> All of the data on Bintray is available for download through May 1st and we encourage you to transfer it out. JFrog will begin **deleting data** several weeks after the official sunset date and will not retain any Bintray data after that. [emphasis mine]

Which sounds like all the packages are going to be deleted in May or June out of Bintray.

While it's not clear, I _suspect_ there is a schedule difference between Bintray and JCenter. The above notice mentions JCenter in the question but not the answer, and the mention of continued package service only says packages will continue to be served from JCenter:

> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.

Given that sqsmock is hosted in Bintray, will it be migrated out before the May 1st shutdown?

**Comment by shuttie** [comment]
Ah, OK, yes bintray is different from jcenter. I will migrate to maven-central before May 1st then.

**Comment by shuttie** [comment]
@Azuaron I've published 0.4.0 to maven central under the same coordinates. It has zero API changes inside, only dependency updates. Readme is also updated to state that bintray is not needed anymore.
