### ISSUE TITLE
Any plans on upgrading SQS Mock to Scala 2.12?

### ISSUE THREAD

**Issue by dazito** [findify/sqsmock#9]
Can't use SQS Mock and S3 Mock because they are using different scala version. So I've to downgrade S3 Mock to scala 2.11 and use a rather limiting version of S3 Mock (no InMemory provider and so on). 

Both libraries are using different scala versions and a `java.util.NoSuchElementException in GraphDSL ` exception occurs on S3 Mock.

Only way to make both libraries work is:
```
		<dependency>
			<groupId>io.findify</groupId>
			<artifactId>s3mock_2.11</artifactId>
			<version>0.1.8</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.findify</groupId>
			<artifactId>sqsmock_2.11</artifactId>
			<version>0.3.2</version>
			<scope>test</scope>
		</dependency>
```

**Comment by dazito** [comment]
Oh, nevermind this issue. I found version S3 Mock v0.2.4 on https://mvnrepository.com/artifact/io.findify/s3mock_2.11

Just to clarify,

```
               <dependency>
			<groupId>io.findify</groupId>
			<artifactId>s3mock_2.11</artifactId>
			<version>0.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.findify</groupId>
			<artifactId>sqsmock_2.11</artifactId>
			<version>0.3.2</version>
			<scope>test</scope>
		</dependency>
```

Works fine!

**Comment by susantamon** [comment]
scala version is upgraded

**Comment by shuttie** [comment]
Migrated to 2.12 in 0.4.0.
